# Generated by Django 5.2.10 on 2026-02-06 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_number', models.CharField(max_length=9, verbose_name='Гос. номер')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('vehicle_type', models.CharField(choices=[('car', 'Легковой автомобиль'), ('truck', 'Грузовик'), ('motorcycle', 'Мотоцикл'), ('bus', 'Автобус')], default='car', max_length=20, verbose_name='Тип ТС')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('processed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отказа')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carowner', verbose_name='Владелец')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_vehicle_requests', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
            ],
            options={
                'verbose_name': 'Запрос на добавление автомобиля',
                'verbose_name_plural': 'Запросы на добавление автомобилей',
                'ordering': ['-request_date'],
            },
        ),
    ]
