# Generated by Django 5.2.10 on 2026-02-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_vehiclerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('saved_filename', models.CharField(max_length=255, verbose_name='Сохраненное имя файла')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('file_size', models.IntegerField(verbose_name='Размер файла (байт)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('completed', 'Обработано'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('detected_license_plate', models.CharField(blank=True, max_length=15, null=True, verbose_name='Распознанный номер')),
            ],
            options={
                'verbose_name': 'Загруженное фото',
                'verbose_name_plural': 'Загруженные фото',
            },
        ),
        migrations.DeleteModel(
            name='VehicleRequest',
        ),
    ]
